name: CGO

on:
  workflow_dispatch:
    inputs:
      ver:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        targets:
          - "!(*musl*|*windows-arm64*|*android*|*freebsd*|*windows7*)"
          - "linux-*-musl*"
          - "windows-arm64"
          - "android-*"
          - "freebsd-*"
          - "windows7-*"

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: make release dir
        run: mkdir -p cgo-build-dist/

      - name: build go program
        id: cgo-action
        uses: go-cross/cgo-actions@v1
        with:
          dir: "."
          targets: ${{ matrix.targets }}
          out-dir: cgo-build-dist/

      - name: print Output
        id: output
        run: echo "${{ steps.cgo-action.outputs.files }}" && ls -alh cgo-build-dist/

      - name: setup 7z
        uses: milliewalky/setup-7-zip@v2
        with:
          tag: "latest"

      - name: compress dist
        env:
          files: ${{ steps.cgo-action.outputs.files }}
        run: |
          cd cgo-build-dist/
          while IFS= read -r line; do
            if [[ -n "$line" ]]; then
              7z a -t7z -m0=lzma2 -mx=9 -md=64m -mfb=273 -ms=on -mmt=on "$line.7z" "$line"
            fi
          done <<< "$files"

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ strategy.job-index }}
          path: cgo-build-dist/*.7z

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: cgo-build-dist/
          merge-multiple: true

      - name: list release files
        run: ls -l cgo-build-dist/

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.ver }}
          files: |
            cgo-build-dist/*
          name: ${{ github.event.inputs.ver }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
